//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectEMSEntities1 : DbContext
    {
        public ProjectEMSEntities1()
            : base("name=ProjectEMSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HR_SignUp> HR_SignUp { get; set; }
        public DbSet<t_Departments> t_Departments { get; set; }
        public DbSet<t_Employees> t_Employees { get; set; }
        public DbSet<t_PersonalInformations> t_PersonalInformations { get; set; }
        public DbSet<holiday> holidays { get; set; }
        public DbSet<t_leaves> t_leaves { get; set; }
        public DbSet<t_payroll> t_payroll { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
